### ISSUE TITLE
Missing some select functionality 

### ISSUE THREAD

**Issue by dmagunov** [novafloss/ember-simple-select#8]
Hello,

Are you planning to add "multiple" and "optgroup" support to your select component?

**Comment by xcambar** [comment]
This not planned as of now.
We built this component because we were tired of the lack of _straightforward_ select element in Ember.

I understand the need for multiple selection and optgroup but it is a rare enough usecase (for us).

If you decide to add it and want to contribute, you are more than welcome!

For a more powerful select component, I would recommend ember-power-select.
